export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia (Czech Republic)",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini (fmr. Swaziland)",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (formerly Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const NEPAL_DISTRICTS = [
  "Achham",
  "Arghakhanchi",
  "Baglung",
  "Baitadi",
  "Bajhang",
  "Bajura",
  "Banke",
  "Bara",
  "Bardiya",
  "Bhaktapur",
  "Bhojpur",
  "Chitwan",
  "Dadeldhura",
  "Dailekh",
  "Dang",
  "Darchula",
  "Dhading",
  "Dhankuta",
  "Dhanusa",
  "Dolakha",
  "Dolpa",
  "Doti",
  "Eastern Rukum",
  "Gorkha",
  "Gulmi",
  "Humla",
  "Ilam",
  "Jajarkot",
  "Jhapa",
  "Jumla",
  "Kailali",
  "Kalikot",
  "Kanchanpur",
  "Kapilvastu",
  "Kaski",
  "Kathmandu",
  "Kavrepalanchok",
  "Khotang",
  "Lalitpur",
  "Lamjung",
  "Mahottari",
  "Makwanpur",
  "Manang",
  "Morang",
  "Mugu",
  "Mustang",
  "Myagdi",
  "Nawalpur",
  "Nuwakot",
  "Okhaldhunga",
  "Palpa",
  "Panchthar",
  "Parasi",
  "Parbat",
  "Parsa",
  "Pyuthan",
  "Ramechhap",
  "Rasuwa",
  "Rautahat",
  "Rolpa",
  "Rupandehi",
  "Salyan",
  "Sankhuwasabha",
  "Saptari",
  "Sarlahi",
  "Sindhuli",
  "Sindhupalchok",
  "Siraha",
  "Solukhumbu",
  "Sunsari",
  "Surkhet",
  "Syangja",
  "Tanahun",
  "Taplejung",
  "Terhathum",
  "Udayapur",
  "Western Rukum",
];

export const NEPAL_CITIES = [
  "Kathmandu",
  "Pokhara",
  "Lalitpur",
  "Bharatpur",
  "Biratnagar",
  "Birgunj",
  "Ghorahi",
  "Tulsipur",
  "Dharan",
  "Itahari",
  "Janakpurdham",
  "Hetauda",
  "Kalaiya",
  "Jitpursimara",
  "Butwal",
  "Nepalgunj",
  "Dhangadhi",
  "Birendranagar",
  "Godawari",
  "Siddharthanagar",
  "Triyuga",
  "Kohalpur",
  "Tilottama",
  "Lahan",
  "Rajbiraj",
  "Siraha",
  "Malangwa",
  "Gaur",
  "Kapilvastu",
  "Sandhikharka",
  "Tansen",
  "Baglung",
  "Waling",
  "Putalibazar",
  "Gorkha",
  "Besishahar",
  "Dhulikhel",
  "Banepa",
  "Panauti",
  "Bhaktapur",
  "Kirtipur",
  "Madhyapur Thimi",
  "Tokha",
  "Budhanilkantha",
  "Gokarneshwar",
  "Tarakeshwar",
  "Chandragiri",
  "Dakshinkali",
  "Shankharapur",
  "Nagarkot",
  "Changunarayan",
  "Suryabinayak",
  "Nilkantha",
  "Dhunibeshi",
  "Ratnanagar",
  "Khairhani",
  "Rapti",
  "Kalika",
  "Madi",
  "Bhadrapur",
  "Birtamode",
  "Damak",
  "Kankai",
  "Mechinagar",
  "Arjundhara",
  "Shivasatakshi",
  "Gauradaha",
  "Urlabari",
  "Rangeli",
  "Pathari-Shanishchare",
  "Letang",
  "Belbari",
  "Sunwarshi",
  "Sundar Haraicha",
  "Inaruwa",
  "Duhabi",
  "Ramdhuni",
  "Ilam",
  "Phidim",
  "Taplejung",
  "Fungling",
  "Dhankuta",
  "Pakhribas",
  "Hile",
  "Bhojpur",
  "Shadananda",
  "Khandbari",
  "Chainpur",
  "Dharmadevi",
  "Barahakshetra",
  "Belaka",
  "Udayapurgadhi",
  "Katari",
  "Chaudandigadhi",
  "Bhimeshwar",
  "Jiri",
  "Manthali",
  "Ramechhap",
  "Melamchi",
  "Barhabise",
  "Chautara",
  "Indrawati",
  "Panchkhal",
  "Mandandeupur",
  "Namobuddha",
  "Kamalamai",
  "Dudhauli",
  "Hariwan",
  "Lalbandi",
  "Ishworpur",
  "Bagmati",
  "Chandrapur",
  "Gujara",
  "Bardibas",
  "Gaushala",
  "Jaleshwar",
  "Manara",
  "Matihani",
  "Bhangaha",
  "Balawa",
  "Loharpatti",
  "Ramgopalpur",
  "Aurahi",
  "Bideha",
  "Kshireshwarnath",
  "Dhanushadham",
  "Sabaila",
  "Ganeshman Charnath",
  "Mithila",
  "Nagarain",
  "Kamala",
  "Bhagwanpur",
  "Mahagadhimai",
  "Simraungadh",
  "Kolhabi",
  "Nijgadh",
  "Jeetpur",
  "Parwanipur",
  "Pokhariya",
  "Bahudarmai",
  "Parsagadhi",
  "Bansgadhi",
  "Gulariya",
  "Madhuwan",
  "Rajapur",
  "Thakurbaba",
  "Tikapur",
  "Lamki",
  "Ghodaghodi",
  "Bhajani",
  "Janaki",
  "Krishnapur",
  "Shuklaphanta",
  "Belauri",
  "Punarbas",
  "Mahendranagar",
  "Bedkot",
  "Dodhara Chandani",
  "Amargadhi",
  "Parshuram",
  "Dasharathchand",
  "Purchaudi",
  "Patan",
  "Melauli",
  "Jayaprithvi",
  "Chainpur Bajhang",
  "Talkot",
  "Shital",
  "Dipayal Silgadhi",
  "Shikhar",
  "Budhiganga",
  "Sanphebagar",
  "Kamalamai",
  "Dhangadhi",
  "Attariya",
  "Lamahi",
  "Gadhawa",
  "Banganga",
  "Kapilvastu",
  "Shivaraj",
  "Krishnanagar",
  "Maharajganj",
  "Ramgram",
  "Sunwal",
  "Devdaha",
  "Sainamaina",
  "Butwal",
  "Tilottama",
  "Resunga",
  "Musikot",
  "Chandrakot",
  "Isma",
  "Ruru",
  "Bhurigaun",
  "Triveni",
  "Salyan",
  "Sharada",
  "Bagchaur",
  "Bangad Kupinde",
  "Jumla",
  "Chandannath",
  "Narayan",
  "Dullu",
  "Aathabis",
  "Chamunda",
  "Mahakali",
  "Shailyashikhar",
  "Bhimdatta",
  "Bedkot",
];
